SistemaCitasRemotas/SistemaCitasRemotas/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//importando bibliotecas
using SistemaCitasRemotas.Models;
using SistemaCitasRemotas.Filters;
using System.Text;
using System.Security.Cryptography;

namespace SistemaCitasRemotas.Controllers
{
    //[Autenticado]
    public class MedicoController : Controller
    {
        // GET: Usuario
        //private Usuario objUsuario = new Usuario();
        private Medico objMedico = new Medico();
        private TipoUsuario objTipoUsuario = new TipoUsuario();
        private Especialidad objEspecialidad = new Especialidad();

        // GET: Semestre
        public ActionResult Index(string criterio)
        {
            if (criterio == null || criterio == "")
            {
                return View(objMedico.Listar());
            }
            else
            {
                return View(objMedico.Buscar(criterio));
            }
        }

        public ActionResult Visualizar(int id)
        {
            return View(objMedico.Obtener(id));
        }

        public ActionResult AgregarEditar(int id = 0)
        {
            ViewBag.TipoUsuario = objTipoUsuario.Listar();
            ViewBag.Especialidad = objEspecialidad.Listar();
            return View(id == 0 ? new Medico() // Agregarmos un nuevo objeto
                : objMedico.Obtener(id) //Devuelve el id del objeto
                );
        }

        public ActionResult Guardar(Medico objMedico)
        {
            if (ModelState.IsValid)
            {
                objMedico.clave= MD5Hash(objMedico.clave);
                objMedico.Guardar();
                return Redirect("~/Medico");
            }
            else
            {
                return View("~/Views/Medico/AgregarEditar.cshtml", objMedico);
            }
        }

        public ActionResult Eliminar(int id)
        {
            objMedico.id = id;
            objMedico.Eliminar();
            return Redirect("~/usuario");
        }

        public static string MD5Hash(string input)
        {
            StringBuilder hash = new StringBuilder();
            MD5CryptoServiceProvider md5provider = new MD5CryptoServiceProvider();
            byte[] bytes = md5provider.ComputeHash(new UTF8Encoding().GetBytes(input));

            for (int i = 0; i < bytes.Length; i++)
            {
                hash.Append(bytes[i].ToString("x2"));
            }
            return hash.ToString();
        }


    }
}

SistemaCitasRemotas/SistemaCitasRemotas/Views/Medico/AgregarEditar.cshtml
@model SistemaCitasRemotas.Models.Medico
@{ ViewBag.Title = "AgregarEditar";
    List<SistemaCitasRemotas.Models.TipoUsuario> TipoUsuario = ViewBag.TipoUsuario;
    List<SistemaCitasRemotas.Models.Especialidad> Especialidad = ViewBag.Especialidad;
}

<h2>Agregar / Editar</h2>   

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="~/Medico/Index">Medico</a></li>
        <li class="breadcrumb-item active">@Model.nombres</li>
    </ol>
</nav>

<br />
<br />

@using (Html.BeginForm("Guardar", "Medico", FormMethod.Post))
{
    @Html.HiddenFor(X => X.id)

    <div class="card">
        <div class="card-header">Informacion del semestre</div>
        <div class="card-body">

            <div class="form-group">
                @Html.LabelFor(x => x.id)
                @Html.TextBoxFor(x => x.id, new { @class = "form-control", disabled = true })
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.idTipoUsuario)
                <select name="idTipoUsuario" class="form-control">
                    <option @(Model.idTipoUsuario.Equals("") ? "selected" : "") value="">Seleccione</option>

                    @foreach (var d in TipoUsuario)
                    {
                        <option @(Model.idTipoUsuario.Equals(d.id) ? "selected" : "") value="@d.id">@d.nombre </option>
                    }
                </select>
                @Html.ValidationMessageFor(x => x.idTipoUsuario, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.idEspecialidad)
                <select name="idEspecialidad" class="form-control">
                    <option @(Model.idEspecialidad.Equals("") ? "selected" : "") value="">Seleccione</option>

                    @foreach (var d in Especialidad)
                    {
                        <option @(Model.idEspecialidad.Equals(d.id) ? "selected" : "") value="@d.id">@d.nombre </option>
                    }
                </select>
                @Html.ValidationMessageFor(x => x.idEspecialidad, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.nombres)
                @Html.TextBoxFor(x => x.nombres, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.nombres, null, new { @class = "text-danger" })
            </div>


            <div class="form-group">
                @Html.LabelFor(x => x.apellidos)
                @Html.TextBoxFor(x => x.apellidos, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.apellidos, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.telefono)
                @Html.TextBoxFor(x => x.telefono, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.telefono, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.correo)
                @Html.TextBoxFor(x => x.correo, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.correo, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.clave)
                @Html.TextBoxFor(x => x.clave, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.clave, null, new { @class = "text-danger" })
            </div>




            <div class="form-group">
                @Html.LabelFor(x => x.estado)
                <select name="estado" class="form-control">
                    <option @(Model.estado == "" ? "selected" : "" ) value="">Seleccion</option>
                    <option @(Model.estado == "activo" ? "selected" : "" ) value="activo">Activo</option>
                    <option @(Model.estado == "inactivo" ? "selected" : "" ) value="inactivo">Inactivo</option>
                </select>
                @Html.ValidationMessageFor(x => x.estado, null, new { @class = "text-danger" })

            </div>


            <div class="text-right">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a href="~/Usuario" class="btn btn-danger">Cancelar</a>
            </div>

        </div>


    </div>}

SistemaCitasRemotas/SistemaCitasRemotas/Views/Medico/Index.cshtml
@model List<SistemaCitasRemotas.Models.Medico>
@{
    ViewBag.Title = "Index";
}

<h2 class="card-header">

    <a href="~/Medico/AgregarEditar/" class="btn btn-info float-right">Nuevo Medico</a>
</h2>

@using (Html.BeginForm("Index", "Medico", FormMethod.Post, new { usuario = "frm-medico" }))
{
    <div class="text-left">
        @Html.Label("Buscar:")
        @Html.TextBox("criterio")
        <button type="submit" class="btn btn-secondary">Buscar</button>
    </div>}


<br />
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>APELLIDO Y NOMBRES</th>
            <th>TELEFONO</th>
            <th>ESTADO</th>
            <th>ACCION</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>@(m.id)</td>
                <td>@(m.nombres),@(m.apellidos)</td>
                <td>@(m.telefono)</td>
                <td>@(m.estado.Equals("activo")?"ACTIVO" : "INACTIVO" )</td>
                <td style="align-content:center">
                    <a href="~/Medico/Visualizar/@m.id" class="btn btn-warning">Detalle</a>
                    <a href="~/Medico/AgregarEditar/@m.id" class="btn btn-primary">Modificar</a>
                    <a href="~/Medico/Eliminar/@m.id" class="btn btn-danger" onclick="return confirm('¿Esta seguro de eliminar el registro?')">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SistemaCitasRemotas/SistemaCitasRemotas/Views/Medico/Visualizar.cshtml
@model SistemaCitasRemotas.Models.Medico
@{
    ViewBag.Title = "Visualizar";
}



<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="~/Medico/Index"></a>Medico</li>
        <li class="breadcrumb-item active">@Model.nombres</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">Informacion del Semestre</div>
    <div class="card-body">
        <dl class="list-group-horizontal">
            <dt>Id</dt>
            <dd>@Model.id</dd>
            <dt>Nombre</dt>
            <dd>@Model.idTipoUsuario</dd>
            <dt>Año</dt>
            <dd>@Model.idEspecialidad</dd>
            <dt>Estado</dt>
            <dd>(@Model.nombres),(@Model.apellidos)</dd>
            <dt>Estado</dt>
            <dd>@Model.telefono</dd>
            <dt>Estado</dt>
            <dd>@Model.correo</dd>
            <dt>Estado</dt>
            <dd>@Model.clave</dd>
            <dt>Estado</dt>
            <dd>@Model.estado</dd>

        </dl>
    </div>
</div>
